import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/header/Header';
import ReactQueryProvider from '@/utils/ReactQueryProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <ReactQueryProvider>
          <LayoutContent children={children} />
        </ReactQueryProvider>
      </body>
    </html>
  );
}

const LayoutContent = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className='wrapper'>
      <Header />
      <main className='mainwrapper'>{children}</main>
    </div>
  );
};
