import type { Metadata } from 'next';
import './globals.css';
import ReactQueryProvider from '@/utils/ReactQueryProvider';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <ReactQueryProvider>
          <LayoutContent children={children} />
          <ReactQueryDevtools initialIsOpen={false} />
        </ReactQueryProvider>
      </body>
    </html>
  );
}

const LayoutContent = ({ children }: { children: React.ReactNode }) => {
  return <>{children}</>;
};
